

// events.js - Database of 200 Global Historical Events
const EVENT_POOL = [
  // Ancient Era (3500 BCE - 500 BCE)
  { title: "Invention of Cuneiform writing in Sumer", year: -3200, yearDisplay: "c. 3200 BCE" },
  { title: "Unification of Upper and Lower Egypt under King Narmer", year: -3100, yearDisplay: "c. 3100 BCE" },
  { title: "Construction of Stonehenge begins", year: -3000, yearDisplay: "c. 3000 BCE" },
  { title: "Rise of the Indus Valley Civilization (Harappa & Mohenjo-Daro)", year: -2600, yearDisplay: "c. 2600 BCE" },
  { title: "Great Pyramid of Giza completed for Pharaoh Khufu", year: -2560, yearDisplay: "c. 2560 BCE" },
  { title: "Minoan civilization emerges on Crete", year: -2000, yearDisplay: "c. 2000 BCE" },
  { title: "Epic of Gilgamesh recorded in Babylonian literature", year: -1800, yearDisplay: "c. 1800 BCE" },
  { title: "Code of Hammurabi inscribed in Babylon", year: -1750, yearDisplay: "c. 1750 BCE" },
  { title: "Shang Dynasty established in China", year: -1600, yearDisplay: "c. 1600 BCE" },
  { title: "Thera volcanic eruption devastates Santorini", year: -1620, yearDisplay: "c. 1620 BCE" },
  { title: "Tomb of King Tutankhamun sealed in the Valley of the Kings", year: -1323, yearDisplay: "1323 BCE" },
  { title: "Battle of Kadesh between Egypt and the Hittite Empire", year: -1274, yearDisplay: "1274 BCE" },
  { title: "Traditional date for the Fall of Troy", year: -1184, yearDisplay: "c. 1184 BCE" },
  { title: "Phoenicians invent the phonetic alphabet", year: -1050, yearDisplay: "c. 1050 BCE" },
  { title: "Kingdom of Israel unified under King David", year: -1000, yearDisplay: "c. 1000 BCE" },
  { title: "First recorded Ancient Olympic Games in Olympia", year: -776, yearDisplay: "776 BCE" },
  { title: "Traditional founding of Rome by Romulus", year: -753, yearDisplay: "753 BCE" },
  { title: "Assyrian conquest of the Northern Kingdom of Israel", year: -722, yearDisplay: "722 BCE" },
  { title: "Solon establishes democratic legal reforms in Athens", year: -594, yearDisplay: "594 BCE" },
  { title: "Babylonian destruction of the First Temple in Jerusalem", year: -586, yearDisplay: "586 BCE" },
  { title: "Cyrus the Great founds the Achaemenid Persian Empire", year: -550, yearDisplay: "550 BCE" },
  { title: "Siddhartha Gautama (The Buddha) attains enlightenment", year: -528, yearDisplay: "c. 528 BCE" },
  { title: "Confucius begins his philosophical teachings in China", year: -510, yearDisplay: "c. 510 BCE" },
  { title: "Roman Republic established following expulsion of Tarquin", year: -509, yearDisplay: "509 BCE" },

  // Classical Antiquity (500 BCE - 476 CE)
  { title: "Battle of Marathon: Athenians defeat the Persian invasion", year: -490, yearDisplay: "490 BCE" },
  { title: "Battle of Thermopylae and Spartan stand under Leonidas", year: -480, yearDisplay: "480 BCE" },
  { title: "Completion of the Parthenon in Athens", year: -432, yearDisplay: "432 BCE" },
  { title: "Peloponnesian War between Athens and Sparta concludes", year: -404, yearDisplay: "404 BCE" },
  { title: "Trial and execution of Socrates in Athens", year: -399, yearDisplay: "399 BCE" },
  { title: "Plato founds the Academy in Athens", year: -387, yearDisplay: "387 BCE" },
  { title: "Alexander the Great defeats Darius III at the Battle of Gaugamela", year: -331, yearDisplay: "331 BCE" },
  { title: "Founding of the Library of Alexandria in Egypt", year: -300, yearDisplay: "c. 300 BCE" },
  { title: "Ashoka the Great converts to Buddhism and rules the Maurya Empire", year: -261, yearDisplay: "261 BCE" },
  { title: "Qin Shi Huang unifies China and standardizes the Great Wall", year: -221, yearDisplay: "221 BCE" },
  { title: "Hannibal crosses the Alps during the Second Punic War", year: -218, yearDisplay: "218 BCE" },
  { title: "Rosetta Stone inscribed under Ptolemy V", year: -196, yearDisplay: "196 BCE" },
  { title: "Roman destruction of Carthage in the Third Punic War", year: -146, yearDisplay: "146 BCE" },
  { title: "Opening of the Silk Road by Han Dynasty envoy Zhang Qian", year: -130, yearDisplay: "c. 130 BCE" },
  { title: "Spartacus leads the Third Servile gladiator rebellion", year: -73, yearDisplay: "73 BCE" },
  { title: "Julius Caesar crosses the Rubicon River", year: -49, yearDisplay: "49 BCE" },
  { title: "Assassination of Julius Caesar on the Ides of March", year: -44, yearDisplay: "44 BCE" },
  { title: "Battle of Actium: Octavian defeats Mark Antony and Cleopatra", year: -31, yearDisplay: "31 BCE" },
  { title: "Octavian receives title Augustus, founding the Roman Empire", year: -27, yearDisplay: "27 BCE" },
  { title: "Crucifixion of Jesus of Nazareth", year: 33, yearDisplay: "33 CE" },
  { title: "Roman Emperor Claudius begins conquest of Britain", year: 43, yearDisplay: "43 CE" },
  { title: "Great Fire of Rome under Emperor Nero", year: 64, yearDisplay: "64 CE" },
  { title: "Destruction of the Second Temple in Jerusalem by Titus", year: 70, yearDisplay: "70 CE" },
  { title: "Eruption of Mount Vesuvius destroys Pompeii and Herculaneum", year: 79, yearDisplay: "79 CE" },
  { title: "Inauguration of the Colosseum in Rome", year: 80, yearDisplay: "80 CE" },
  { title: "Cai Lun invents improved papermaking in China", year: 105, yearDisplay: "105 CE" },
  { title: "Roman Empire reaches maximum territorial extent under Trajan", year: 117, yearDisplay: "117 CE" },
  { title: "Construction of Hadrian's Wall across northern Britain", year: 122, yearDisplay: "122 CE" },
  { title: "Emperor Caracalla grants Roman citizenship to all free imperial subjects", year: 212, yearDisplay: "212 CE" },
  { title: "Emperor Constantine issues the Edict of Milan legalizing Christianity", year: 313, yearDisplay: "313 CE" },
  { title: "First Council of Nicaea establishes orthodox Christian creed", year: 325, yearDisplay: "325 CE" },
  { title: "Constantinople dedicated as the new capital of the Roman Empire", year: 330, yearDisplay: "330 CE" },
  { title: "Visigoths sack Rome under King Alaric", year: 410, yearDisplay: "410 CE" },
  { title: "Deposition of Romulus Augustulus marks Fall of Western Roman Empire", year: 476, yearDisplay: "476 CE" },

  // Early & High Middle Ages (500 - 1300)
  { title: "King Clovis unites the Frankish tribes under Christianity", year: 496, yearDisplay: "496 CE" },
  { title: "Emperor Justinian I completes the compilation of the Corpus Juris Civilis", year: 529, yearDisplay: "529 CE" },
  { title: "Consecration of the Hagia Sophia in Constantinople", year: 537, yearDisplay: "537 CE" },
  { title: "Grand Canal of China construction begins under the Sui Dynasty", year: 605, yearDisplay: "605 CE" },
  { title: "The Hegira: Prophet Muhammad travels from Mecca to Medina", year: 622, yearDisplay: "622 CE" },
  { title: "Umayyad Caliphate captures Jerusalem", year: 637, yearDisplay: "637 CE" },
  { title: "Charles Martel defeats the Umayyads at the Battle of Tours", year: 732, yearDisplay: "732 CE" },
  { title: "Abbasid Caliphate founded; capital moves to Baghdad", year: 750, yearDisplay: "750 CE" },
  { title: "Construction of the Great Mosque of Córdoba begins", year: 784, yearDisplay: "784 CE" },
  { title: "Viking raid on Lindisfarne monastery marks start of Viking Age", year: 793, yearDisplay: "793 CE" },
  { title: "Pope Leo III crowns Charlemagne Holy Roman Emperor", year: 800, yearDisplay: "800 CE" },
  { title: "Founding of the House of Wisdom in Baghdad", year: 830, yearDisplay: "c. 830 CE" },
  { title: "Treaty of Verdun divides Charlemagne's empire into three realms", year: 843, yearDisplay: "843 CE" },
  { title: "Rurik establishes the Rurik dynasty in Novgorod (Origins of Kievan Rus')", year: 862, yearDisplay: "862 CE" },
  { title: "Diamond Sutra printed in China (earliest dated complete printed book)", year: 868, yearDisplay: "868 CE" },
  { title: "Althing, the national parliament of Iceland, is founded", year: 930, yearDisplay: "930 CE" },
  { title: "Vladimir the Great converts Kievan Rus' to Orthodox Christianity", year: 988, yearDisplay: "988 CE" },
  { title: "Leif Erikson establishes short-lived Norse settlement in Newfoundland", year: 1000, yearDisplay: "c. 1000 CE" },
  { title: "Avicenna (Ibn Sina) writes The Canon of Medicine", year: 1025, yearDisplay: "1025 CE" },
  { title: "The East-West Schism permanently divides Catholic and Orthodox churches", year: 1054, yearDisplay: "1054 CE" },
  { title: "William the Conqueror defeats King Harold II at the Battle of Hastings", year: 1066, yearDisplay: "1066 CE" },
  { title: "Compilation of the Domesday Book in England", year: 1086, yearDisplay: "1086 CE" },
  { title: "University of Bologna founded (oldest university in continuous operation)", year: 1088, yearDisplay: "1088 CE" },
  { title: "Pope Urban II preaches the First Crusade at the Council of Clermont", year: 1095, yearDisplay: "1095 CE" },
  { title: "Crusaders capture Jerusalem in the First Crusade", year: 1099, yearDisplay: "1099 CE" },
  { title: "Construction of Angkor Wat temple complex in Cambodia begins", year: 1150, yearDisplay: "c. 1150 CE" },
  { title: "Saladin recaptures Jerusalem from the Crusaders", year: 1187, yearDisplay: "1187 CE" },
  { title: "Fourth Crusade sacks Christian Constantinople", year: 1204, yearDisplay: "1204 CE" },
  { title: "Genghis Khan unites nomadic tribes and proclaims Mongol Empire", year: 1206, yearDisplay: "1206 CE" },
  { title: "King John of England seals the Magna Carta at Runnymede", year: 1215, yearDisplay: "1215 CE" },
  { title: "Mongol forces destroy Baghdad, ending the Abbasid Caliphate", year: 1258, yearDisplay: "1258 CE" },
  { title: "Kublai Khan establishes the Yuan Dynasty in China", year: 1271, yearDisplay: "1271 CE" },
  { title: "Marco Polo departs Venice for his 24-year journey to China", year: 1271, yearDisplay: "1271 CE" },
  { title: "Osman I founds the Ottoman Empire in Anatolia", year: 1299, yearDisplay: "1299 CE" },

  // Late Middle Ages & Renaissance (1300 - 1599)
  { title: "Mansa Musa embarks on his lavish, gold-laden pilgrimage to Mecca", year: 1324, yearDisplay: "1324 CE" },
  { title: "Outbreak of the Hundred Years' War between England and France", year: 1337, yearDisplay: "1337 CE" },
  { title: "The Black Death enters European ports, killing millions", year: 1347, yearDisplay: "1347 CE" },
  { title: "Geoffrey Chaucer begins writing The Canterbury Tales", year: 1387, yearDisplay: "1387 CE" },
  { title: "Battle of Agincourt: Henry V's archers defeat the French army", year: 1415, yearDisplay: "1415 CE" },
  { title: "Joan of Arc relieves the Siege of Orléans for the French crown", year: 1429, yearDisplay: "1429 CE" },
  { title: "Johannes Gutenberg invents movable type printing in Mainz", year: 1440, yearDisplay: "1440 CE" },
  { title: "Fall of Constantinople to Sultan Mehmed II of the Ottoman Empire", year: 1453, yearDisplay: "1453 CE" },
  { title: "Inca ruler Pachacuti begins expansion of Tawantinsuyu (Inca Empire)", year: 1438, yearDisplay: "c. 1438 CE" },
  { title: "Spanish Catholic Monarchs complete the Reconquista at Granada", year: 1492, yearDisplay: "1492 CE" },
  { title: "Christopher Columbus reaches the Bahamas in the Americas", year: 1492, yearDisplay: "1492 CE" },
  { title: "Treaty of Tordesillas divides New World between Spain and Portugal", year: 1494, yearDisplay: "1494 CE" },
  { title: "Vasco da Gama arrives in Calicut, India via the Cape of Good Hope", year: 1498, yearDisplay: "1498 CE" },
  { title: "Leonardo da Vinci completes the Mona Lisa", year: 1503, yearDisplay: "1503 CE" },
  { title: "Michelangelo unveils the marble statue of David in Florence", year: 1504, yearDisplay: "1504 CE" },
  { title: "Michelangelo completes painting the Sistine Chapel ceiling", year: 1512, yearDisplay: "1512 CE" },
  { title: "Martin Luther posts 95 Theses at Wittenberg, sparking Reformation", year: 1517, yearDisplay: "1517 CE" },
  { title: "Hernán Cortés enters Tenochtitlan and begins conquest of Aztec Empire", year: 1519, yearDisplay: "1519 CE" },
  { title: "Magellan-Elcano expedition completes first circumnavigation of Earth", year: 1522, yearDisplay: "1522 CE" },
  { title: "Babur wins the Battle of Panipat, founding the Mughal Empire", year: 1526, yearDisplay: "1526 CE" },
  { title: "Francisco Pizarro captures Inca Emperor Atahualpa at Cajamarca", year: 1532, yearDisplay: "1532 CE" },
  { title: "Henry VIII passes the Act of Supremacy, breaking England from Rome", year: 1534, yearDisplay: "1534 CE" },
  { title: "Copernicus publishes De revolutionibus orbium coelestium", year: 1543, yearDisplay: "1543 CE" },
  { title: "Coronation of Ivan the Terrible as the first Tsar of All Russia", year: 1547, yearDisplay: "1547 CE" },
  { title: "St. Bartholomew's Day massacre targeting French Huguenots", year: 1572, yearDisplay: "1572 CE" },
  { title: "English fleet under Drake and Howard defeats the Spanish Armada", year: 1588, yearDisplay: "1588 CE" },
  { title: "Henry IV of France signs the Edict of Nantes granting religious rights", year: 1598, yearDisplay: "1598 CE" },

  // Early Modern & Enlightenment (1600 - 1799)
  { title: "British East India Company is granted its Royal Charter", year: 1600, yearDisplay: "1600 CE" },
  { title: "Founding of Jamestown, Virginia (first permanent English colony in US)", year: 1607, yearDisplay: "1607 CE" },
  { title: "Galileo Galilei turns his astronomical telescope toward the night sky", year: 1609, yearDisplay: "1609 CE" },
  { title: "Publication of the King James Bible in England", year: 1611, yearDisplay: "1611 CE" },
  { title: "The Mayflower lands English Pilgrims at Plymouth Rock", year: 1620, yearDisplay: "1620 CE" },
  { title: "Construction of the Taj Mahal begins in Agra under Shah Jahan", year: 1632, yearDisplay: "1632 CE" },
  { title: "Trial of Galileo Galilei by the Roman Inquisition", year: 1633, yearDisplay: "1633 CE" },
  { title: "Execution of King Charles I of England following English Civil War", year: 1649, yearDisplay: "1649 CE" },
  { title: "Peace of Westphalia ends the Thirty Years' War in Europe", year: 1648, yearDisplay: "1648 CE" },
  { title: "The Great Fire of London devastates medieval city center", year: 1666, yearDisplay: "1666 CE" },
  { title: "Antonie van Leeuwenhoek discovers single-celled microorganisms", year: 1674, yearDisplay: "1674 CE" },
  { title: "Battle of Vienna: Ottoman siege lifted by Polish King Jan Sobieski", year: 1683, yearDisplay: "1683 CE" },
  { title: "Isaac Newton publishes the Philosophiæ Naturalis Principia Mathematica", year: 1687, yearDisplay: "1687 CE" },
  { title: "Peter the Great founds the coastal city of Saint Petersburg", year: 1703, yearDisplay: "1703 CE" },
  { title: "Acts of Union unite Kingdom of England and Kingdom of Scotland", year: 1707, yearDisplay: "1707 CE" },
  { title: "James Watt patents the improved condensing steam engine", year: 1769, yearDisplay: "1769 CE" },
  { title: "James Cook arrives at Botany Bay, Australia aboard HMS Endeavour", year: 1770, yearDisplay: "1770 CE" },
  { title: "Boston Tea Party political protest against British taxation", year: 1773, yearDisplay: "1773 CE" },
  { title: "Battles of Lexington and Concord initiate American Revolutionary War", year: 1775, yearDisplay: "1775 CE" },
  { title: "Second Continental Congress adopts the US Declaration of Independence", year: 1776, yearDisplay: "1776 CE" },
  { title: "Adam Smith publishes The Wealth of Nations", year: 1776, yearDisplay: "1776 CE" },
  { title: "Treaty of Paris signed, recognizing independence of the United States", year: 1783, yearDisplay: "1783 CE" },
  { title: "First Fleet arrives in Botany Bay, establishing penal colony in Sydney", year: 1788, yearDisplay: "1788 CE" },
  { title: "Storming of the Bastille marks outbreak of the French Revolution", year: 1789, yearDisplay: "1789 CE" },
  { title: "Haitian Revolution begins under Toussaint Louverture", year: 1791, yearDisplay: "1791 CE" },
  { title: "Execution of King Louis XVI of France by guillotine", year: 1793, yearDisplay: "1793 CE" },
  { title: "Edward Jenner administers the first successful smallpox vaccine", year: 1796, yearDisplay: "1796 CE" },
  { title: "French soldiers discover the Rosetta Stone near Rashid, Egypt", year: 1799, yearDisplay: "1799 CE" },

  // 19th Century (1800 - 1899)
  { title: "United States completes the Louisiana Purchase from France", year: 1803, yearDisplay: "1803 CE" },
  { title: "Napoleon Bonaparte crowns himself Emperor of the French", year: 1804, yearDisplay: "1804 CE" },
  { title: "Battle of Trafalgar: Royal Navy defeats Franco-Spanish fleet", year: 1805, yearDisplay: "1805 CE" },
  { title: "United Kingdom abolishes the transatlantic slave trade", year: 1807, yearDisplay: "1807 CE" },
  { title: "Miguel Hidalgo issues the Cry of Dolores, launching Mexican Independence", year: 1810, yearDisplay: "1810 CE" },
  { title: "Napoleon's Grande Armée retreats from Moscow with catastrophic losses", year: 1812, yearDisplay: "1812 CE" },
  { title: "Duke of Wellington defeats Napoleon at the Battle of Waterloo", year: 1815, yearDisplay: "1815 CE" },
  { title: "Simón Bolívar proclaims the independence of Gran Colombia", year: 1819, yearDisplay: "1819 CE" },
  { title: "Opening of the Erie Canal in New York State", year: 1825, yearDisplay: "1825 CE" },
  { title: "George Stephenson's Rocket locomotive wins the Rainhill Trials", year: 1829, yearDisplay: "1829 CE" },
  { title: "Battle of the Alamo during the Texas Revolution", year: 1836, yearDisplay: "1836 CE" },
  { title: "Samuel Morse publicly demonstrates the electric telegraph", year: 1838, yearDisplay: "1838 CE" },
  { title: "Treaty of Waitangi signed between British Crown and Māori chiefs", year: 1840, yearDisplay: "1840 CE" },
  { title: "The Great Famine devastates Ireland", year: 1845, yearDisplay: "1845 CE" },
  { title: "Revolutions of 1848 erupt across continental Europe", year: 1848, yearDisplay: "1848 CE" },
  { title: "Karl Marx and Friedrich Engels publish The Communist Manifesto", year: 1848, yearDisplay: "1848 CE" },
  { title: "Discovery of gold at Sutter's Mill launches California Gold Rush", year: 1848, yearDisplay: "1848 CE" },
  { title: "Taiping Rebellion breaks out against the Qing Dynasty in China", year: 1850, yearDisplay: "1850 CE" },
  { title: "Commodore Matthew Perry's Black Ships force opening of Japan", year: 1853, yearDisplay: "1853 CE" },
  { title: "Charge of the Light Brigade at the Battle of Balaclava", year: 1854, yearDisplay: "1854 CE" },
  { title: "Sepoy Mutiny (First War of Indian Independence) against British rule", year: 1857, yearDisplay: "1857 CE" },
  { title: "Charles Darwin publishes On the Origin of Species", year: 1859, yearDisplay: "1859 CE" },
  { title: "Confederate bombardment of Fort Sumter begins American Civil War", year: 1861, yearDisplay: "1861 CE" },
  { title: "Tsar Alexander II issues the Emancipation Edict freeing Russian serfs", year: 1861, yearDisplay: "1861 CE" },
  { title: "Abraham Lincoln issues the Emancipation Proclamation", year: 1863, yearDisplay: "1863 CE" },
  { title: "Battle of Gettysburg marks major turning point in US Civil War", year: 1863, yearDisplay: "1863 CE" },
  { title: "Assassination of President Abraham Lincoln by John Wilkes Booth", year: 1865, yearDisplay: "1865 CE" },
  { title: "Gregor Mendel formulates the fundamental laws of genetic inheritance", year: 1866, yearDisplay: "1866 CE" },
  { title: "Meiji Restoration overthrows Tokugawa Shogunate in Japan", year: 1868, yearDisplay: "1868 CE" },
  { title: "Opening of the Suez Canal linking the Mediterranean to the Red Sea", year: 1869, yearDisplay: "1869 CE" },
  { title: "First Transcontinental Railroad joined at Promontory Summit, Utah", year: 1869, yearDisplay: "1869 CE" },
  { title: "Dmitri Mendeleev publishes the first Periodic Table of Elements", year: 1869, yearDisplay: "1869 CE" },
  { title: "Proclamation of the German Empire at Versailles under Bismarck", year: 1871, yearDisplay: "1871 CE" },
  { title: "Alexander Graham Bell receives patent for the telephone", year: 1876, yearDisplay: "1876 CE" },
  { title: "Thomas Edison patents the commercial incandescent light bulb", year: 1880, yearDisplay: "1880 CE" },
  { title: "Berlin Conference partitions the African continent among European powers", year: 1884, yearDisplay: "1884 CE" },
  { title: "Karl Benz patents the Benz Patent-Motorwagen (first modern car)", year: 1886, yearDisplay: "1886 CE" },
  { title: "Statue of Liberty dedicated in New York Harbor", year: 1886, yearDisplay: "1886 CE" },
  { title: "Eiffel Tower completed for the Paris Exposition Universelle", year: 1889, yearDisplay: "1889 CE" },
  { title: "New Zealand becomes first nation granting women the right to vote", year: 1893, yearDisplay: "1893 CE" },
  { title: "Wilhelm Röntgen discovers X-rays", year: 1895, yearDisplay: "1895 CE" },
  { title: "First modern Olympic Games held in Athens, Greece", year: 1896, yearDisplay: "1896 CE" },
  { title: "Marie and Pierre Curie discover the radioactive elements Polonium & Radium", year: 1898, yearDisplay: "1898 CE" },
  { title: "Boxer Rebellion targets foreign influence in China", year: 1899, yearDisplay: "1899 CE" },

  // 20th Century: Part 1 (1900 - 1949)
  { title: "Guglielmo Marconi sends the first transatlantic radio transmission", year: 1901, yearDisplay: "1901 CE" },
  { title: "Wright Brothers make the first powered airplane flight at Kitty Hawk", year: 1903, yearDisplay: "1903 CE" },
  { title: "Albert Einstein publishes his Special Theory of Relativity", year: 1905, yearDisplay: "1905 CE" },
  { title: "San Francisco earthquake and subsequent firestorms", year: 1906, yearDisplay: "1906 CE" },
  { title: "Roald Amundsen's Norwegian expedition reaches the South Pole", year: 1911, yearDisplay: "1911 CE" },
  { title: "Xinhai Revolution overthrows the Qing Dynasty, ending Imperial China", year: 1911, yearDisplay: "1911 CE" },
  { title: "Sinking of the RMS Titanic on its maiden voyage", year: 1912, yearDisplay: "1912 CE" },
  { title: "Henry Ford introduces the continuous moving automobile assembly line", year: 1913, yearDisplay: "1913 CE" },
  { title: "Opening of the Panama Canal", year: 1914, yearDisplay: "1914 CE" },
  { title: "Assassination of Archduke Franz Ferdinand in Sarajevo ignites WWI", year: 1914, yearDisplay: "1914 CE" },
  { title: "Sinking of the RMS Lusitania by German U-boat", year: 1915, yearDisplay: "1915 CE" },
  { title: "Battle of the Somme commences with massive casualties", year: 1916, yearDisplay: "1916 CE" },
  { title: "Bolsheviks under Vladimir Lenin seize power in the Russian Revolution", year: 1917, yearDisplay: "1917 CE" },
  { title: "Spanish Flu global pandemic breaks out worldwide", year: 1918, yearDisplay: "1918 CE" },
  { title: "Signing of the Treaty of Versailles ending World War I", year: 1919, yearDisplay: "1919 CE" },
  { title: "Nineteenth Amendment ratified, guaranteeing American women right to vote", year: 1920, yearDisplay: "1920 CE" },
  { title: "Howard Carter discovers the intact tomb of Pharaoh Tutankhamun", year: 1922, yearDisplay: "1922 CE" },
  { title: "Mustafa Kemal Atatürk proclaims the secular Republic of Turkey", year: 1923, yearDisplay: "1923 CE" },
  { title: "Charles Lindbergh completes first solo nonstop transatlantic flight", year: 1927, yearDisplay: "1927 CE" },
  { title: "Alexander Fleming discovers the antibacterial properties of Penicillin", year: 1928, yearDisplay: "1928 CE" },
  { title: "Black Tuesday Wall Street Stock Market Crash triggers Great Depression", year: 1929, yearDisplay: "1929 CE" },
  { title: "Mahatma Gandhi leads the Salt March civil disobedience campaign", year: 1930, yearDisplay: "1930 CE" },
  { title: "Amelia Earhart completes solo transatlantic flight", year: 1932, yearDisplay: "1932 CE" },
  { title: "Adolf Hitler appointed Chancellor of Germany", year: 1933, yearDisplay: "1933 CE" },
  { title: "Mao Zedong leads Chinese Red Army on the Long March", year: 1934, yearDisplay: "1934 CE" },
  { title: "Hindenburg airship disaster in Lakehurst, New Jersey", year: 1937, yearDisplay: "1937 CE" },
  { title: "Nazi invasion of Poland marks official outbreak of World War II in Europe", year: 1939, yearDisplay: "1939 CE" },
  { title: "Evacuation of Allied forces from Dunkirk beaches", year: 1940, yearDisplay: "1940 CE" },
  { title: "Japanese aerial attack on Pearl Harbor brings United States into WWII", year: 1941, yearDisplay: "1941 CE" },
  { title: "Battle of Midway: US Navy sinks four Japanese aircraft carriers", year: 1942, yearDisplay: "1942 CE" },
  { title: "Soviet victory at the Battle of Stalingrad turns tide of WWII", year: 1943, yearDisplay: "1943 CE" },
  { title: "D-Day: Allied amphibious invasion of Normandy beaches", year: 1944, yearDisplay: "1944 CE" },
  { title: "United Nations Charter signed by 50 nations in San Francisco", year: 1945, yearDisplay: "1945 CE" },
  { title: "Atomic bombings of Hiroshima and Nagasaki, Japan", year: 1945, yearDisplay: "1945 CE" },
  { title: "Nuremberg Trials begin against prominent Nazi war criminals", year: 1945, yearDisplay: "1945 CE" },
  { title: "Eniac, the first programmable general-purpose electronic computer, dedicated", year: 1946, yearDisplay: "1946 CE" },
  { title: "Partition of British India establishes independent India and Pakistan", year: 1947, yearDisplay: "1947 CE" },
  { title: "State of Israel proclaimed by David Ben-Gurion", year: 1948, yearDisplay: "1948 CE" },
  { title: "Berlin Airlift begins in response to Soviet blockade", year: 1948, yearDisplay: "1948 CE" },
  { title: "Universal Declaration of Human Rights adopted by the UN General Assembly", year: 1948, yearDisplay: "1948 CE" },
  { title: "Mao Zedong proclaims the founding of the People's Republic of China", year: 1949, yearDisplay: "1949 CE" },
  { title: "North Atlantic Treaty signed, establishing NATO alliance", year: 1949, yearDisplay: "1949 CE" },

  // 20th Century: Part 2 (1950 - 1999)
  { title: "Outbreak of the Korean War across the 38th parallel", year: 1950, yearDisplay: "1950 CE" },
  { title: "James Watson and Francis Crick discover the DNA double helix", year: 1953, yearDisplay: "1953 CE" },
  { title: "Sir Edmund Hillary and Tenzing Norgay make first summit of Mount Everest", year: 1953, yearDisplay: "1953 CE" },
  { title: "US Supreme Court rules school segregation unconstitutional in Brown v. Board", year: 1954, yearDisplay: "1954 CE" },
  { title: "Jonas Salk's polio vaccine declared safe and effective worldwide", year: 1955, yearDisplay: "1955 CE" },
  { title: "Rosa Parks refuses to give up her bus seat, sparking Montgomery Bus Boycott", year: 1955, yearDisplay: "1955 CE" },
  { title: "Hungarian Revolution crushed by Soviet military intervention", year: 1956, yearDisplay: "1956 CE" },
  { title: "Treaty of Rome establishes the European Economic Community (EEC)", year: 1957, yearDisplay: "1957 CE" },
  { title: "Soviet Union launches Sputnik 1, the first artificial orbital satellite", year: 1957, yearDisplay: "1957 CE" },
  { title: "Cuban Revolution concludes as Fidel Castro assumes power", year: 1959, yearDisplay: "1959 CE" },
  { title: "Soviet cosmonaut Yuri Gagarin becomes first human in space", year: 1961, yearDisplay: "1961 CE" },
  { title: "Construction of the Berlin Wall begins in East Germany", year: 1961, yearDisplay: "1961 CE" },
  { title: "Cuban Missile Crisis brings the world to the brink of nuclear war", year: 1962, yearDisplay: "1962 CE" },
  { title: "Martin Luther King Jr. delivers 'I Have a Dream' speech in Washington DC", year: 1963, yearDisplay: "1963 CE" },
  { title: "Assassination of President John F. Kennedy in Dallas, Texas", year: 1963, yearDisplay: "1963 CE" },
  { title: "President Lyndon B. Johnson signs the landmark US Civil Rights Act", year: 1964, yearDisplay: "1964 CE" },
  { title: "Six-Day War alters geopolitical boundaries in the Middle East", year: 1967, yearDisplay: "1967 CE" },
  { title: "Dr. Christiaan Barnard performs the world's first human heart transplant", year: 1967, yearDisplay: "1967 CE" },
  { title: "Assassination of Martin Luther King Jr. in Memphis, Tennessee", year: 1968, yearDisplay: "1968 CE" },
  { title: "Apollo 11 astronauts Neil Armstrong and Buzz Aldrin walk on the Moon", year: 1969, yearDisplay: "1969 CE" },
  { title: "Woodstock music and art festival held in Bethel, New York", year: 1969, yearDisplay: "1969 CE" },
  { title: "Creation of ARPANET, transmitting first node-to-node message", year: 1969, yearDisplay: "1969 CE" },
  { title: "President Richard Nixon makes historic diplomatic visit to China", year: 1972, yearDisplay: "1972 CE" },
  { title: "President Richard Nixon resigns in the wake of the Watergate scandal", year: 1974, yearDisplay: "1974 CE" },
  { title: "Fall of Saigon concludes the Vietnam War", year: 1975, yearDisplay: "1975 CE" },
  { title: "Apple Computer Company founded by Steve Jobs and Steve Wozniak", year: 1976, yearDisplay: "1976 CE" },
  { title: "Voyager 1 space probe launched to explore outer solar system", year: 1977, yearDisplay: "1977 CE" },
  { title: "Iranian Revolution overthrows the Shah, establishing Islamic Republic", year: 1979, yearDisplay: "1979 CE" },
  { title: "World Health Organization certifies global eradication of smallpox", year: 1980, yearDisplay: "1980 CE" },
  { title: "IBM releases the Personal Computer (IBM PC model 5150)", year: 1981, yearDisplay: "1981 CE" },
  { title: "Live Aid global concert raises funds for Ethiopian famine relief", year: 1985, yearDisplay: "1985 CE" },
  { title: "Space Shuttle Challenger explodes seconds after liftoff", year: 1986, yearDisplay: "1986 CE" },
  { title: "Chernobyl nuclear reactor disaster in Soviet Ukraine", year: 1986, yearDisplay: "1986 CE" },
  { title: "Tiananmen Square protests and military crackdown in Beijing", year: 1989, yearDisplay: "1989 CE" },
  { title: "Fall of the Berlin Wall", year: 1989, yearDisplay: "1989 CE" },
  { title: "Nelson Mandela is released from Victor Verster Prison after 27 years", year: 1990, yearDisplay: "1990 CE" },
  { title: "Hubble Space Telescope deployed into low Earth orbit", year: 1990, yearDisplay: "1990 CE" },
  { title: "Dissolution of the Soviet Union formally ends the Cold War", year: 1991, yearDisplay: "1991 CE" },
  { title: "Tim Berners-Lee releases the World Wide Web source code to the public", year: 1993, yearDisplay: "1993 CE" },
  { title: "End of Apartheid in South Africa as Nelson Mandela elected President", year: 1994, yearDisplay: "1994 CE" },
  { title: "Dolly the Sheep is successfully cloned from an adult mammary gland cell", year: 1996, yearDisplay: "1996 CE" },
  { title: "Signing of the Good Friday Agreement in Northern Ireland", year: 1998, yearDisplay: "1998 CE" },
  { title: "First module of the International Space Station (ISS) launched", year: 1998, yearDisplay: "1998 CE" },
  { title: "Euro currency officially introduced for financial transactions", year: 1999, yearDisplay: "1999 CE" },

  // 21st Century (2000 - Present)
  { title: "Human Genome Project publishes initial working draft of the genetic code", year: 2000, yearDisplay: "2000 CE" },
  { title: "Launch of Wikipedia free online encyclopedia", year: 2001, yearDisplay: "2001 CE" },
  { title: "Terrorist attacks on the World Trade Center and Pentagon on 9/11", year: 2001, yearDisplay: "2001 CE" },
  { title: "Founding of Facebook at Harvard University by Mark Zuckerberg", year: 2004, yearDisplay: "2004 CE" },
  { title: "Indian Ocean earthquake and catastrophic tsunami", year: 2004, yearDisplay: "2004 CE" },
  { title: "Apple introduces the original touchscreen iPhone", year: 2007, yearDisplay: "2007 CE" },
  { title: "Global financial crisis triggered by subprime mortgage market collapse", year: 2008, yearDisplay: "2008 CE" },
  { title: "Barack Obama inaugurated as the first African American US President", year: 2009, yearDisplay: "2009 CE" },
  { title: "Arab Spring protests begin across North Africa and the Middle East", year: 2010, yearDisplay: "2010 CE" },
  { title: "Tōhoku earthquake, tsunami, and Fukushima Daiichi nuclear disaster in Japan", year: 2011, yearDisplay: "2011 CE" },
  { title: "Physicists at CERN confirm discovery of the Higgs Boson particle", year: 2012, yearDisplay: "2012 CE" },
  { title: "Paris Climate Agreement adopted by consensus of 196 nations", year: 2015, yearDisplay: "2015 CE" },
  { title: "LIGO observatory makes first direct observation of gravitational waves", year: 2015, yearDisplay: "2015 CE" },
  { title: "United Kingdom votes to leave the European Union (Brexit referendum)", year: 2016, yearDisplay: "2016 CE" },
  { title: "Event Horizon Telescope reveals first direct image of a supermassive black hole", year: 2019, yearDisplay: "2019 CE" },
  { title: "World Health Organization declares the global COVID-19 pandemic", year: 2020, yearDisplay: "2020 CE" },
  { title: "NASA's Perseverance rover successfully lands in Jezero Crater on Mars", year: 2021, yearDisplay: "2021 CE" },
  { title: "James Webb Space Telescope transmits its first operational deep-field images", year: 2022, yearDisplay: "2022 CE" }
];